Added "dotenv" dependency to package.json
freeCodeCamp/boilerplate-project-headerparser pull request #18
Opened 2021-01-17 11:00 UTC by ZaidAli5430

Since the project is using .env file for fetching the port, it had no `dotenv` dependency. This creates confusion when `process.env.PORT` doesn't work. I hope this is convenient for beginners :+1:

2021-01-17 17:34 UTC, SaintPeter commented
If we're going to use this, might want to add the require/setup statement in the `server.js` file?

2021-01-17 18:22 UTC, ZaidAli5430 commented
@SaintPeter yeh right. So should I create a new pull request?

2021-01-17 18:51 UTC, ZaidAli5430 commented
@SaintPeter I have updated the `server.js` file. I hope it's good now.

2021-01-18 03:03 UTC, SaintPeter commented
LGTM!  🎊

2021-01-18 12:50 UTC, ShaunSHamilton requested changes
Hey @ZaidAli5430 . Thank you, for this PR.

Would you mind also pushing the changes to the `package-lock.json`?

2021-01-18 16:42 UTC, ZaidAli5430 commented
@ShaunSHamilton I have made the requested change. Please review and let me know if it's good or not.

2021-01-18 18:41 UTC, ShaunSHamilton approved these changes
This LGTM 👍 

Thanks, for making that change. @SaintPeter Are you still happy with these changes?

2021-01-18 19:01 UTC, SaintPeter commented
@ShaunSHamilton Yup, pretty simple, LGTM.

2021-01-18 19:07 UTC, ZaidAli5430 commented
@ShaunSHamilton @SaintPeter  Thank you so much. This is my first ever open source contribution and I don't know how I am going to be able to sleep tonight.

2021-01-18 23:37 UTC, merged

2021-01-18 23:37 UTC, ShaunSHamilton commented
Congrats on your first pull request (PR)! 🎉

Thank you, for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝